path: A:\Projects\AircraftIdentificationAI\dataset # dataset root directory
train: ../split_dataset/train # train images (relative to 'path')
val: ../split_dataset/val # val images (relative to 'path')

# Classes
names:
  0: Aircraft
  1: Jet
  2: Multi Engine
  3: Single Engine
  